services:
  api:
    build: .
    container_name: api_eventos
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./src:/app

  database:
    image: postgres:15-alpine
    container_name: database_eventos
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data/

volumes:
  pg_data: