# Generated by Django 5.2.6 on 2025-09-12 18:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='uuid_code',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=128, null=True, unique=True),
        ),
    ]
