# Generated by Django 5.2.6 on 2025-09-11 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_code', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('deletado_em', models.DateTimeField(blank=True, null=True, verbose_name='Data de deleção')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
                ('complemento', models.CharField(blank=True, max_length=255, verbose_name='Complemento')),
                ('cep', models.CharField(max_length=20, verbose_name='Cep')),
                ('numero', models.CharField(max_length=20, verbose_name='Número')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=100, verbose_name='Estado')),
                ('comeca_as', models.DateTimeField(verbose_name='Horário que começa')),
                ('termina_as', models.DateTimeField(verbose_name='Horário que termina')),
                ('max_inscricoes', models.PositiveIntegerField(verbose_name='Máximo de inscrições permitidas')),
                ('is_ativo', models.BooleanField(default=True, verbose_name='Está ativo?')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
        migrations.CreateModel(
            name='EventoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_code', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('deletado_em', models.DateTimeField(blank=True, null=True, verbose_name='Data de deleção')),
            ],
            options={
                'verbose_name': 'Evento e convidado',
                'verbose_name_plural': 'Eventos e convidados',
            },
        ),
    ]
